LOGGING:
    LEVEL: DEBUG
    DIR: 'D:/temp/var/log/software_registry/services'

AMQP_URI: 'amqp://localhost'

REDIS_URIS:
    services: 'redis://127.0.0.1:6379/1'
    development: 'redis://127.0.0.1:6379/1'
