version: "3"

services:
    webserver:
        image: daydreamer/softreg-nginx:v1
        ports:
            - 80:80
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    msg_queue:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    cache:
        image: redis:latest
        ports:
            - 6379:6379
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    db:
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    app:
        image: daydreamer/softreg-app:v1
        ports:
            - 4000:4000
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    registry_service:
        image: daydreamer/softreg-registry-service:v1
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
