#!/usr/bin/env bash

# As a client you need to obtain the client key, please replace the client key placeholder's with yours.

# obtain client-key
curl -X POST http://localhost:5000/api/auth/client-key

# api home
curl http://localhost:5000/api?client-key=5b7aaad77caf4b4fb76159af30ccf9e2

# add repos 
curl -X POST -H "Content-Type: application/json" -d '{"name": "alembic-base", "description": "The base of alembic caches.", "downloads": 342, "uri": "alembic-base.v1", "tags": ["\"alembic file format\"", "\"vfx pipeline\""]}' http://localhost:5000/api/repos?client-key=5b7aaad77caf4b4fb76159af30ccf9e2
curl -X POST -H "Content-Type: application/json" -d '{"name": "usd_dev:v2", "description": "Second version of USD in Docker development.", "downloads": 250, "uri": "usd_dev.v2", "tags": ["docker usd", "\"vfx pipeline\""]}' http://localhost:5000/api/repos?client-key=5b7aaad77caf4b4fb76159af30ccf9e2
curl -X POST -H "Content-Type: application/json" -d '{"name": "usd_dev:anim", "description": "Production version of USD in Docker for feature animation pipeline.", "downloads": 410, "uri": "usd_dev.anim", "tags": ["docker usd"]}' http://localhost:5000/api/repos?client-key=5b7aaad77caf4b4fb76159af30ccf9e2
curl -X POST -H "Content-Type: application/json" -d '{"name":"nodes editor","description": "Generic Qt Node editor.","downloads": 500,"uri": "nodes_editor.v1","tags": ["node graph qt", "\"vfx pipeline\""]}' http://localhost:5000/api/repos?client-key=5b7aaad77caf4b4fb76159af30ccf9e2
curl -X POST -H "Content-Type: application/json" -d '{"name":"usd_standalone","description": "Standalone USD workflow.","downloads": 467,"uri": "usd_standalone.v1","tags": ["\"universal scene description\"","\"vfx pipeline\""]}' http://localhost:5000/api/repos?client-key=5b7aaad77caf4b4fb76159af30ccf9e2

# get repos from tags
curl 'http://localhost:5000/api/repos?tag=node%20graph%20qt&tag=%22alembic%20file%20format%22&client-key=5b7aaad77caf4b4fb76159af30ccf9e2'

