LOGGING:
    LEVEL: 'debug'
    FORMATTER: 'debug'
    FILE: 'D:/temp/var/log/software_registry/services/registry.log'

AMQP_URI: 'amqp://localhost'

REDIS_URIS:
    services: 'redis://127.0.0.1:6379/1'
    development: 'redis://127.0.0.1:6379/1'
