FROM python:3

MAINTAINER Anurag Bisht <day.dreamer.3d@gmail.com>

COPY ./registry/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt \
&& rm /tmp/requirements.txt

COPY ./registry /registry
COPY ./_utils /_utils
COPY ./base.py /base.py
COPY ./config.yml /config.yml

RUN chmod +x ./registry/entrypoint.py

ENTRYPOINT ["python"]
CMD ["-m", "registry.entrypoint"]
