LOGGING:
    LEVEL: 'DEBUG'
    DIR: '/var/log/software_registry/services'

CACHE:
    KEY: 'software_registry:services:registry'

INSTANCES: 2

DB_URIS:
    'registry:Base': 'mysql+pymysql://root:1234@db:3306/registry'
